---
# tasks file for mac-setup

- name: ensure Node packages are present
  npm: name={{ item }} global=yes
  with_items:
    - bower 
    - less 
    - uglify 
    - uglify-js 
    - node-sass


- cpanm:
    name: YAML::XS
    system_lib: yes


# before doing this, the /usr/local/bin/mysql_config should be changed with a patch like this
#-libs="-L$pkglibdir  -lmariadb -lz -liconv -lssl -lcrypto"
#+libs="-L$pkglibdir -L/usr/local/opt/openssl@1.1/lib -lmariadb -lz -liconv -lssl -lcrypto"

 
#-include="-I$pkgincludedir"
#+include="-I$pkgincludedir -I/usr/local/Cellar/openssl@1.1/include"

- cpanm:
    name: DBD::mysql
    system_lib: yes
    notest: yes

- name: Copy bash profile
  copy:
    src: .bash_profile
    dest: ~/.bash_profile


- name: Copy mysql config
  copy:
    src: .my.cnf
    dest: ~/.my.cnf

- name: Create directories
  file: path={{item}} state=directory mode=0755
  with_items:
    - /Users/aghaffar/Downloads/screenshots
    - /Users/aghaffar/projects/worldsoft
    - /Users/aghaffar/projects/wa

- name: Copy git config
  copy:
    src: gitconfig
    dest: ~/.gitconfig

- name: Copy apache config
  copy:
    src: httpd.conf
    dest: /usr/local/etc/httpd/httpd.conf



# install all projects
- name: git clone projects
  git:
    repo: "{{ item.value.git }}"
    dest: "/Users/aghaffar/projects/{{ item.value.dir }}"
    version: "{{ item.value.branch }}"
    update: no
    accept_hostkey: yes
    key_file: "/Users/aghaffar/.ssh/id_rsa"
  with_dict: "{{ projects }}"





- name: Hide Dock completely
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.dock autohide -bool true 
    - defaults write com.apple.dock autohide-delay -float 1000
    - defaults write com.apple.dock no-bouncing -bool TRUE 
    - killall Dock
  tags: ['never', 'dock']




- name: Change location for screenshots
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.screencapture location /Users/aghaffar/Downloads/screenshots/
    - killall SystemUIServer

- name: Setup a cron to backup
  cron:
    user: aghaffar
    name: "backup2rsync"
    minute: "00"
    hour: "*"
    job: "/usr/bin/perl /Users/aghaffar/projects/mac-setup/files/bin/backup2rsync.net.pl"
